version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://admin:secure_password@mongodb:27017/projectalpha?authSource=admin
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config:ro

  redis:
    image: redis:7-alpine

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure_password # pragma: allowlist secret
